[2025-07-18T11:47:08.755+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.ingest_data manual__2025-07-18T11:47:07.852790+00:00 [queued]>
[2025-07-18T11:47:08.760+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: mlops_retrain_pipeline.ingest_data manual__2025-07-18T11:47:07.852790+00:00 [queued]>
[2025-07-18T11:47:08.761+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T11:47:08.761+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-07-18T11:47:08.761+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-07-18T11:47:08.768+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): ingest_data> on 2025-07-18 11:47:07.852790+00:00
[2025-07-18T11:47:08.772+0000] {standard_task_runner.py:55} INFO - Started process 175 to run task
[2025-07-18T11:47:08.775+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'mlops_retrain_pipeline', 'ingest_data', 'manual__2025-07-18T11:47:07.852790+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/retrain_dag.py', '--cfg-path', '/tmp/tmpozekqtwt']
[2025-07-18T11:47:08.780+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask ingest_data
[2025-07-18T11:47:08.825+0000] {task_command.py:389} INFO - Running <TaskInstance: mlops_retrain_pipeline.ingest_data manual__2025-07-18T11:47:07.852790+00:00 [running]> on host 24fa8db10c0a
[2025-07-18T11:47:08.869+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=mlops_retrain_pipeline
AIRFLOW_CTX_TASK_ID=ingest_data
AIRFLOW_CTX_EXECUTION_DATE=2025-07-18T11:47:07.852790+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-07-18T11:47:07.852790+00:00
[2025-07-18T11:47:08.870+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2025-07-18T11:47:08.871+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /app/scripts/ingest.py mode=ingest']
[2025-07-18T11:47:08.876+0000] {subprocess.py:86} INFO - Output:
[2025-07-18T11:47:09.005+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-07-18T11:47:09.005+0000] {subprocess.py:93} INFO -   File "/app/scripts/ingest.py", line 3, in <module>
[2025-07-18T11:47:09.005+0000] {subprocess.py:93} INFO -     from src.data.ingestion import DataIngestor
[2025-07-18T11:47:09.006+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'src'
[2025-07-18T11:47:09.021+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-18T11:47:09.029+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-18T11:47:09.031+0000] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=mlops_retrain_pipeline, task_id=ingest_data, execution_date=20250718T114707, start_date=20250718T114708, end_date=20250718T114709
[2025-07-18T11:47:09.040+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 3 for task ingest_data (Bash command failed. The command returned a non-zero exit code 1.; 175)
[2025-07-18T11:47:09.079+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-07-18T11:47:09.092+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
